<!-- <div class="faq-click faq">
    <a href="#"><?php //echo __('FAQ'); ?></a>
</div> -->
<div class="consulting-content" id="consulting-content">
    <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('koian')->toHtml(); ?>
</div>

<script>
    require([
        'jquery',
        'Magento_Ui/js/modal/modal'
        ], function($, modal) {
         $(document).ajaxComplete(function() {
            $('<button type="button" class="button action primary checkout faq-click" style="width: auto; margin-left: 5px;" value="Place Proposal"><span>FAQ</span></button>').insertAfter($('.action.primary.checkout'));

            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                title: ''
            };

            var slide = modal(options, $('#consulting-content'));

            $('.faq-click span').on('click', function() {
                $('#consulting-content').modal('openModal');
                return false;
            });
        });  
        // declaring initial options

    });
</script>